photo/config/routes.rb
Rails.application.routes.draw do
  root  'users#top'
  get   '/top',                  to:'users#top',              as: :top
  get   '/sign_up',              to:'users#sign_up',          as: :sign_up
  post  '/sign_up',              to:'users#sign_up_process',  as: :sign_up_process
  get   '/sign_in',              to:'users#sign_in',          as: :sign_in
  post  '/sign_in',              to:'users#sign_in_process',  as: :sign_in_process
  get   '/sign_out',             to:'users#sign_out',         as: :sign_out
  get   '/profile/(:id)',        to:'users#show',             as: :profile
  post  '/profile/edit',         to:'users#update',           as: :profile_edit
  get   '/follower_list/(:id)',  to:'users#follower_list',    as: :follower_list
  get   '/follow_list/(:id)',    to:'users#follow_list',      as: :follow_list
  post  '/posts',                to:'posts#create',           as: :posts
  resources :posts
end

photo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

photo/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_images, dependent: :destroy
end

photo/app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
end

photo/app/models/user.rb
class User < ApplicationRecord
  # リレーション
  has_many :posts
 
  # データの保存前に、パスワードを暗号化するメソッド(convert_password)を実行するよう設定
  before_save :convert_password
  
  # バリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  validates :password, presence: true, length:{minimum: 6}
 
  # パスワードを暗号化するメソッド
  def convert_password
    self.password = User.generate_password(self.password)
  end
 
  # パスワードをmd5に変換するメソッド
  def self.generate_password(password)
    # パスワードに適当な文字列を付加して暗号化する
    salt = "h!hgamcRAdh38bajhvgai17ysvb"
    Digest::MD5.hexdigest(salt + password)
  end
end

photo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper
end

photo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize
  
  # 新規投稿ページ
  def new
    @post = Post.new
  end
  
  # 投稿処理
  def create
    # パラメータ受け取り
    @post = Post.new(post_params)
    upload_file = params[:post][:upload_file]
    
    # 投稿画像がない場合
    if upload_file.blank?
      flash[:danger] = "投稿には画像が必須です。"
      redirect_to new_post_path and return
    end
    
    # 画像のファイル名取得
    upload_file_name = upload_file.original_filename
    output_dir = Rails.root.join('public', 'images')
    output_path = output_dir + upload_file_name
    
    # 画像のアップロード
    File.open(output_path, 'w+b') do |f|
      f.write(upload_file.read)
    end
    
    # post_imagesテーブルに登録するファイル名をPostインスタンスに格納
    @post.post_images.new(name: upload_file_name)
    
    # データベースに保存
    if @post.save
      # 登録したらtopページへ
      flash[:success] = '投稿しました'
      redirect_to top_path
    else
      # 登録が失敗したら投稿ページへ
      flash[:danger] = "投稿に失敗しました。"
      redirect_to posts_path
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:caption).merge(user_id: current_user.id)
  end
end

photo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
  before_action :redirect_to_top_if_signed_in, only: [:sign_up, :sign_in]

  # ユーザー登録
  def sign_up
    @user = User.new
    render layout: "application_not_login"
  end

  def sign_up_process
    @user = User.new(user_params) 
    if @user.save
      # 登録が成功したらサインインしてトップページへ
      user_sign_in(@user)
      redirect_to top_path and return
    else
      # 登録が失敗したらユーザー登録ページへ
      flash[:danger] = "ユーザー登録に失敗しました。"
      redirect_to sign_up_path
    end
  end

  # ログイン処理
  def sign_in
    @user = User.new
    render layout: "application_not_login"
  end

  def sign_in_process
    # パスワードをmd5に変換
    password_md5 = User.generate_password(user_params[:password])
    user = User.find_by(email: user_params[:email], password: password_md5)
    if user
      # セッション処理
      user_sign_in(user)
      # トップ画面へ遷移する
      redirect_to top_path and return
    end
  end
  
  # サインアウト処理
  def sign_out
    # ユーザーセッションを破棄
    user_sign_out
    # サインインページへ遷移
    redirect_to sign_in_path and return
  end

  def top
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def edit
    @user = User.find(current_user.id)
    upload_file = params[:user][:image]
    if upload_file.present?
      # あった場合はこの中の処理が実行される
    end
  end

  def follower_list
  end
  
  def follow_list
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
end

photo/app/helpers/application_helper.rb
module ApplicationHelper
end

photo/app/helpers/posts_helper.rb
module PostsHelper
end

photo/app/helpers/users_helper.rb
module UsersHelper
  # 渡されたユーザーでサインインする
  def user_sign_in(user)
    session[:user_id] = user.id
  end

  # 現在サインイン中のユーザー情報を返す
  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end
  
  # サインアウトする
  def user_sign_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # ユーザーがサインインしていればtrue, そうでなければfalseを返す
  def user_signed_in?
    current_user.present?
  end
  
  # 認証チェック
  def authorize
    redirect_to sign_in_path unless user_signed_in?
  end
  
  # サインイン済みならトップページに遷移する
  def redirect_to_top_if_signed_in
    redirect_to top_path and return if user_signed_in?
  end
  
  # プロフィール画像がなかったらダミー画像を指定する
  def image_url(user)
    if user.image.blank?
      "https://dummyimage.com/200x200/000/fff"
    else
      "/users/#{user.image}"
    end
  end
end

photo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>
  <body class="logined">
    <header class="global_header">
      <!-- ロゴ -->
      <div class="icon">
        <%= link_to top_path do %>
          <i class="fa fa-camera"></i>
        <% end %>
      </div>
      <%= link_to top_path do %>
        <h1 class="logo">Photo</h1>
      <% end %>
      <!-- 検索フォーム -->
      <form class="search">
        <input type="text" placeholder="検索ワードを入力" name="word" value="">
      </form>
      <!-- メニュー -->
      <ul class="menu">
        <li>
          <!--サインアウト -->
          <%= link_to sign_out_path do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </li>
        <li>
          <!-- プロフィールページ -->
          <%= link_to profile_path(current_user.id) do %>
            <i class="fa fa-user-o"></i>
          <% end %>
        </li>
        <li>
          <!-- 投稿 -->
          <%= link_to new_post_path do %>
            <i class="fa fa-upload"></i>
          <% end %>
        </li>
      </ul>
    </header>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function() {
        $(".alert").slideUp();
      }, 3000);
    </script>
  </body>
</html>

photo/app/views/layouts/application_not_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </body>
</html>

photo/app/views/posts/new.html.erb
<div class="container">
  <div class="new_post_wrap">
    <h1>新規Photo投稿</h1>
    <%= form_for @post do |f| %>
      <!-- ファイル選択ボタン -->
      <div class="file_wrap">
        <%= f.file_field :upload_file %>
      </div>
      <!-- 説明文 -->
      <div class="textarea_wrap">
        <%= f.text_area :caption, placeholder: "写真に対する説明文を入力" %>
      </div>
      <!-- 送信ボタン -->
      <div class="btn_wrap">
        <%= f.submit "送信" %>
      </div>
    <% end %>
  </div>
</div>

photo/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

photo/app/views/users/edit.html.erb
<div class="profile_edit container">
  <%= form_for @user, url: profile_edit_path, method: :post do |f| %>
    <div class="field">
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, placeholder: "名前を入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, placeholder: "メールアドレスを入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :comment, "コメント" %>
      <%= f.text_field :comment, placeholder: "自己紹介など" %>
    </div>
    <div class="field">
      <label>プロフィール画像</label>
      <div class="file_wrap">
        <%= f.file_field :image %>
      </div>
    </div>
    <div class="button_wrap">
      <input type="submit" value="保存する" class="button">
    </div>
  <% end %>
</div>

photo/app/views/users/follow_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <div class="profile">
    <div class="image">
      <div style="background: url('https://dummyimage.com/200/df81a2/fff'); background-position: 50%; background-size: cover;"></div>
    </div>
    <div class="info">
      <div class="name">
        <h1>渡辺はるか</h1>
        <div class="actions">
          <div class="edit">
            <a href="#">プロフィール編集</a>
          </div>
        </div>
      </div>
      <div class="status">
        <p class="posts_count">投稿数3件</p>
        <p class="follower_count"><a href="#">フォロワー1人</a></p>
        <p class="follow_count"><a href="#">3人をフォロー中</a></p>
      </div>
      <div class="comment">
        コードキャンプの渡辺はるかです！よろしくね♪
      </div>
    </div>
  </div>
  <!-- フォローリスト部分 -->
  <h1>フォロー</h1>
  <ul class="users">
    <li>
      <div style="background: url('https://dummyimage.com/200/b492cc/fff'); background-position: 50%; background-size: cover;" class="image"></div>
      <a href="#">
        <span class="name">田上士郎</span>
      </a>
      <a class="button" href="#">フォロー解除</a>
    </li>
    <li>
      <div style="background: url('https://dummyimage.com/200/fbe481/fff'); background-position: 50%; background-size: cover;" class="image"></div>
      <a href="#">
        <span class="name">中山五郎</span>
      </a>
      <a class="button" href="#">フォロー解除</a>
    </li>
    <li>
      <div style="background: url('https://dummyimage.com/200/64c99b/fff'); background-position: 50%; background-size: cover;" class="image"></div>
      <a href="#">
        <span class="name">山上睦郎</span>
      </a>
      <a class="button" href="#">フォロー解除</a>
    </li>
  </ul>
</div>

photo/app/views/users/follower_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <div class="profile">
    <div class="image">
      <div style="background: url('https://dummyimage.com/200/df81a2/fff'); background-position: 50%; background-size: cover;"></div>
    </div>
    <div class="info">
      <div class="name">
        <h1>渡辺はるか</h1>
        <div class="actions">
          <div class="edit">
            <a href="#">プロフィール編集</a>
          </div>
        </div>
      </div>
      <div class="status">
        <p class="posts_count">投稿数3件</p>
        <p class="follower_count"><a href="#">フォロワー1人</a></p>
        <p class="follow_count"><a href="#">3人をフォロー中</a></p>
      </div>
      <div class="comment">
        コードキャンプの渡辺はるかです！よろしくね♪
      </div>
    </div>
  </div>
  <!-- フォロワーリスト部分 -->
  <h1>フォロワー</h1>
  <ul class="users">
    <li>
      <div style="background: url('https://dummyimage.com/200/b492cc/fff'); background-position: 50%; background-size: cover;" class="image"></div>
      <a href="#">
        <span class="name">田上士郎</span>
      </a>
      <a class="button" href="#">フォロー解除</a>
    </li>
  </ul>
</div>

photo/app/views/users/show.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <div class="profile">
    <div class="image">
      <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
    </div>
    <div class="info">
      <div class="name">
        <h1>渡辺はるか</h1>
        <div class="actions">
          <% if @user.id == current_user.id %>
          <div class="edit">
            <%= link_to "プロフィール編集", profile_edit_path %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="status">
        <p class="posts_count">投稿数 <%= @user.posts.length %>件</p>
        <p class="follower_count"><a href="#">フォロワー1人</a></p>
        <p class="follow_count"><a href="#">3人をフォロー中</a></p>
      </div>
      <div class="comment">
        コードキャンプの渡辺はるかです！よろしくね♪
      </div>
    </div>
  </div>
  <!-- 投稿画像部分 -->
  <div class="posts">
    <ul>
      <% @posts.each do |post| %>
        <% post.post_images.each do |post_image| %>
        <li>
          <div style="background: url('<%= "/images/#{post_image.name}" %>'); background-repeat: no-repeat; background-position: 50%;"></div>
        </li>
        <% end %>
      <% end %>
      </ul>
  </div>
</div>

photo/app/views/users/sign_in.html.erb
<div class="sign_in">
  <div class="contents">
    <div class="sign_in_form">
      <h1>Photo</h1>
      <%= form_for @user, url: sign_in_path do |f| %>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>サインインする</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？</p>
      <%= link_to sign_up_path do %>新規登録する<% end %>
    </div>
  </div>
</div>

photo/app/views/users/sign_up.html.erb
<div class="sign_up">
  <div class="contents">
    <div class="sign_up_form">
      <h1>Photo</h1>
      <p>友達のphotoをチェックしよう</p>
      <%= form_for @user, url: sign_up_path do |f| %>
        <div class="field">
          <%= f.text_field :name, placeholder: "ユーザーネーム" %>
        </div>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>登録する</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to sign_in_path do %>サインインする<% end %></p>
    </div>
  </div>
</div>

photo/app/views/users/top.html.erb
<div class="top container">
  <ul class="posts">
    <!-- 投稿画像１つめ -->
    <li>
      <!-- 投稿者のアイコン -->
      <div class="user">
        <div class="icon image" style="background: url('https://dummyimage.com/200/df81a2/fff'); background-position: center; background-size: cover"></div>
        <p><a href="#">渡辺はるか</a></p>
      </div>
      <!-- 投稿画像 -->
      <div class="image_wrap">
        <img src="https://dummyimage.com/600/6b6b6b/fff">
      </div>
      <!-- テキスト部分 -->
      <div class="info">
        <div class="action">
          <a href="#">
            <i class="fa fa-heart-o"></i><!-- いいねを押してない時のハート -->
          </a>
          <label for="post-comment-">
            <i class="fa fa-comment-o"></i>
          </label>
          <a href="#">
            <i class="fa fa-close"></i>
          </a>
        </div>
        <div class="like">
          <p>いいね 3件</p>
        </div>
        <!-- コメント部分 -->
        <div class="comment">
          <ul>
            <!-- 投稿者のキャプション -->
            <li>
              <span class="user_name">渡辺はるか</span>
              <span class="caption">はじめまして！</span>
            </li>
            <!-- 画像へのコメント -->
            <li>
              <span class="user_name">田中一郎</span>
              <span class="caption">こんにちは〜</span>
            </li>
          </ul>
          <!-- コメント入力部分 -->
          <div class="text_wrap">
            <form method="post" action="#">
              <div class="field">
                <input type="text" name="comment" id="post-comment-" placeholder="コメントを入力">
                <input type="submit" value="送信">
              </div>
            </form>
          </div>
        </div>
      </div>
    </li>
    <!-- 投稿画像２つめ -->
    <li>
      <!-- 投稿者のアイコン -->
      <div class="user">
        <div class="icon image" style="background: url('https://dummyimage.com/200/6eb7db/fff'); background-position: center; background-size: cover"></div>
        <p><a href="#">山田次郎</a></p>
      </div>
      <!-- 投稿画像 -->
      <div class="image_wrap">
        <img src="https://dummyimage.com/600/6b6b6b/fff">
      </div>
      <!-- テキスト部分 -->
      <div class="info">
        <div class="action">
          <a href="#">
            <i class="fa fa-heart active"></i><!-- いいねを押した時のハート -->
          </a>
          <label for="post-comment-">
            <i class="fa fa-comment-o"></i>
          </label>
        </div>
        <div class="like">
          <p>いいね 1件</p>
        </div>
        <!-- コメント部分 -->
        <div class="comment">
          <ul>
            <!-- 投稿者のキャプション -->
            <li>
              <span class="user_name">山田次郎</span>
              <span class="caption">Hello！</span>
            </li>
          </ul>
          <!-- コメント入力部分 -->
          <div class="text_wrap">
            <form method="post" action="#">
              <div class="field">
                <input type="text" name="comment" id="post-comment-" placeholder="コメントを入力">
                <input type="submit" value="送信">
              </div>
            </form>
          </div>
        </div>
      </div>
    </li>
  </ul>
  <!-- おすすめユーザー -->
  <div class="recommend">
    <h2>おすすめ</h2>
    <ul>
      <li>
        <a href="#">
          <img src="https://dummyimage.com/200/f6d580/fff">
          <p>田中一郎</p>
        </a>
        <a class="button" href="#">フォローする</a>
      </li>
      <li>
        <a href="#">
          <img src="https://dummyimage.com/200/6eb7db/fff">
            <p>山田次郎</p>
        </a>
        <a class="button" href="#">フォローする</a>
      </li>
      <li>
        <a href="#">
          <img src="https://dummyimage.com/200/cfe283/fff">
          <p>山中三郎</p>
        </a>
        <a class="button" href="#">フォローする</a>
      </li>
    </ul>
  </div>
</div>